apiVersion: 1

datasources:
  - name: AirMonitor SQLite
    uid: airmonitor-sqlite
    type: frser-sqlite-datasource
    access: proxy
    isDefault: true
    editable: false
    jsonData:
      path: /var/lib/airmonitor/airmonitor.sqlite3
